[package]
name = "tyrus_test_utils"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
tempfile = "3.10"
# We include dependencies that generated code might use, to ensure they are available in the temp environment

[lints]
workspace = true
