[package]
name = "integration_tests"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[dependencies]
tyrus_orchestrator = { path = "../crates/tyrus_orchestrator" }
tyrus_test_utils = { path = "../crates/tyrus_test_utils" }
tyrus_parser = { path = "../crates/tyrus_parser" }
tyrus_analyzer = { path = "../crates/tyrus_analyzer" }
assert_cmd = "2.2"
predicates = "3.1"
insta = "1.47"
tempfile = "3.25"
serde_json = "1.0"
trybuild = "1.0"

[dev-dependencies]
