[package]
name = "tyrus_parser"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
swc_ecma_parser = "45.1.1"
swc_ecma_ast = "29.0.0"
swc_common = { version = "26.0.0", features = ["tty-emitter"] }
tyrus_diagnostics = { path = "../tyrus_diagnostics" }
miette = { version = "7.6.0", features = ["fancy"] }

[lints]
workspace = true
