[package]
name = "tyrus_parser"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
swc_ecma_parser = "39.0.2"
swc_ecma_ast = "23.0.0"
swc_common = { version = "21.0.1", features = ["tty-emitter"] }
tyrus_ast = { path = "../tyrus_ast" }
tyrus_diagnostics = { path = "../tyrus_diagnostics" }
miette = { version = "7.6.0", features = ["fancy"] }
